#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Generate the POD6 documentation for the class Date::Calendar::Hijri
#

export DOC=$THIS_DIR/doc

raku --doc=HTML lib/Date/Calendar/Hijri.rakumod        > $DOC/Hijri.html
raku --doc=HTML lib/Date/Calendar/Hijri/Names.rakumod  > $DOC/Hijri-Names.html

case $1 in
   --show)
     cd $DOC
     firefox Hijri.html Hijri-Names.html
     ;;
esac
